// Mock data para desarrollo sin MongoDB
export const mockVacancies = [
  {
    _id: '1',
    title: 'Desarrollador Full Stack Senior',
    department: 'Tecnología',
    location: 'Ciudad de México (Remoto)',
    employmentType: 'full-time',
    description: 'Buscamos un desarrollador full stack con experiencia en React y Node.js',
    optimizedDescription: 'Únete a nuestro equipo como Desarrollador Full Stack Senior y lidera proyectos innovadores usando las últimas tecnologías.',
    salary: { min: 40000, max: 60000, currency: 'MXN' },
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Next.js'],
    experienceYears: 5,
    status: 'published',
    aiAgentId: 'Desarrollador de Software Senior', // Template asignado
    createdAt: '2025-01-15T00:00:00.000Z',
    updatedAt: '2025-01-15T00:00:00.000Z',
  },
  {
    _id: '2',
    title: 'Diseñador UX/UI',
    department: 'Diseño',
    location: 'Guadalajara (Remoto)',
    employmentType: 'full-time',
    description: 'Diseñador creativo con experiencia en interfaces de usuario',
    optimizedDescription: 'Buscamos un Diseñador UX/UI apasionado por crear experiencias digitales excepcionales.',
    salary: { min: 30000, max: 45000, currency: 'MXN' },
    requiredSkills: ['Figma', 'Adobe XD', 'UI Design', 'Prototyping'],
    experienceYears: 3,
    status: 'published',
    aiAgentId: 'Diseñador UX/UI Senior', // Template asignado
    createdAt: '2025-01-16T00:00:00.000Z',
    updatedAt: '2025-01-16T00:00:00.000Z',
  },
  {
    _id: '3',
    title: 'Gerente de Marketing Digital',
    department: 'Marketing',
    location: 'Monterrey (Híbrido)',
    employmentType: 'full-time',
    description: 'Profesional de marketing con experiencia en campañas digitales',
    optimizedDescription: 'Lidera nuestra estrategia de marketing digital y haz crecer nuestra presencia en línea.',
    salary: { min: 35000, max: 50000, currency: 'MXN' },
    requiredSkills: ['SEO', 'SEM', 'Google Analytics', 'Social Media', 'Content Marketing'],
    experienceYears: 4,
    status: 'published',
    aiAgentId: 'Gerente de Marketing Digital', // Template asignado
    createdAt: '2025-01-17T00:00:00.000Z',
    updatedAt: '2025-01-17T00:00:00.000Z',
  },
  {
    _id: '4',
    title: 'Analista de Datos',
    department: 'Tecnología',
    location: 'Ciudad de México (Presencial)',
    employmentType: 'full-time',
    description: 'Analista con experiencia en visualización de datos y SQL',
    optimizedDescription: 'Conviértete en nuestro Analista de Datos y ayuda a tomar decisiones basadas en información.',
    salary: { min: 28000, max: 40000, currency: 'MXN' },
    requiredSkills: ['SQL', 'Python', 'Tableau', 'Power BI', 'Excel'],
    experienceYears: 2,
    status: 'published',
    aiAgentId: 'Analista de Datos', // Template asignado
    createdAt: '2025-01-18T00:00:00.000Z',
    updatedAt: '2025-01-18T00:00:00.000Z',
  },
  {
    _id: '5',
    title: 'Practicante de Ventas',
    department: 'Ventas',
    location: 'León (Presencial)',
    employmentType: 'internship',
    description: 'Estudiante para prácticas en área de ventas',
    optimizedDescription: 'Inicia tu carrera en ventas con nosotros. Aprende de los mejores.',
    salary: { min: 8000, max: 12000, currency: 'MXN' },
    requiredSkills: ['Comunicación', 'Excel', 'CRM'],
    experienceYears: 0,
    status: 'published',
    aiAgentId: 'Practicante Junior', // Template asignado
    createdAt: '2025-01-19T00:00:00.000Z',
    updatedAt: '2025-01-19T00:00:00.000Z',
  },
  {
    _id: '6',
    title: 'DevOps Engineer',
    department: 'Tecnología',
    location: 'Remoto',
    employmentType: 'full-time',
    description: 'Ingeniero DevOps para gestionar infraestructura cloud',
    optimizedDescription: 'Únete como DevOps Engineer y optimiza nuestra infraestructura en la nube.',
    salary: { min: 45000, max: 65000, currency: 'MXN' },
    requiredSkills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    experienceYears: 4,
    status: 'published',
    aiAgentId: 'Desarrollador de Software Senior', // Template asignado (reutilizando)
    createdAt: '2025-01-20T00:00:00.000Z',
    updatedAt: '2025-01-20T00:00:00.000Z',
  },
  {
    _id: '7',
    title: 'Product Manager',
    department: 'Producto',
    location: 'Ciudad de México (Híbrido)',
    employmentType: 'full-time',
    description: 'Product Manager para liderar desarrollo de productos',
    optimizedDescription: 'Lidera la visión de producto y trabaja con equipos multidisciplinarios.',
    salary: { min: 50000, max: 75000, currency: 'MXN' },
    requiredSkills: ['Product Strategy', 'Agile', 'Scrum', 'User Research', 'Roadmapping'],
    experienceYears: 5,
    status: 'published',
    aiAgentId: 'Gerente de Proyectos Senior', // Template asignado
    createdAt: '2025-01-21T00:00:00.000Z',
    updatedAt: '2025-01-21T00:00:00.000Z',
  },
  {
    _id: '8',
    title: 'Contador Senior',
    department: 'Finanzas',
    location: 'Querétaro (Presencial)',
    employmentType: 'full-time',
    description: 'Contador con experiencia en finanzas corporativas',
    optimizedDescription: 'Gestiona las finanzas de nuestra empresa en crecimiento.',
    salary: { min: 32000, max: 48000, currency: 'MXN' },
    requiredSkills: ['Contabilidad', 'SAT', 'Excel', 'Auditoría', 'Finanzas'],
    experienceYears: 5,
    status: 'published',
    aiAgentId: 'Especialista en Finanzas', // Template asignado
    createdAt: '2025-01-22T00:00:00.000Z',
    updatedAt: '2025-01-22T00:00:00.000Z',
  },
  {
    _id: '9',
    title: 'Gerente de Recursos Humanos',
    department: 'Recursos Humanos',
    location: 'Puebla (Híbrido)',
    employmentType: 'full-time',
    description: 'Profesional de RRHH para liderar equipo',
    optimizedDescription: 'Lidera nuestra estrategia de talento y cultura organizacional.',
    salary: { min: 38000, max: 55000, currency: 'MXN' },
    requiredSkills: ['Reclutamiento', 'Nómina', 'Relaciones Laborales', 'Capacitación'],
    experienceYears: 6,
    status: 'published',
    aiAgentId: 'Especialista en Recursos Humanos', // Template asignado
    createdAt: '2025-01-23',
    updatedAt: '2025-01-23',
  },
  {
    _id: '10',
    title: 'Ingeniero de QA',
    department: 'Tecnología',
    location: 'Tijuana (Remoto)',
    employmentType: 'full-time',
    description: 'Ingeniero de calidad para pruebas automatizadas',
    optimizedDescription: 'Asegura la calidad de nuestros productos con pruebas automatizadas.',
    salary: { min: 30000, max: 45000, currency: 'MXN' },
    requiredSkills: ['Selenium', 'Jest', 'Cypress', 'API Testing', 'Automation'],
    experienceYears: 3,
    status: 'published',
    aiAgentId: 'Desarrollador de Software Senior', // Template asignado
    createdAt: '2025-01-24',
    updatedAt: '2025-01-24',
  },
];

export const mockCandidates = [
  {
    _id: 'c1',
    vacancyId: '1',
    fullName: 'Carlos Martínez',
    email: 'carlos.martinez@email.com',
    phone: '+52 55 1234 5678',
    cvPath: '/uploads/cvs/carlos-martinez.pdf',
    status: 'applied',
    aiAnalysis: {
      score: 92,
      classification: 'ideal',
      summary: 'Candidato excepcional con 6 años de experiencia en desarrollo full stack.',
      strengths: ['React experto', 'Node.js avanzado', 'TypeScript', 'Arquitectura de software'],
      concerns: ['Ninguna preocupación significativa'],
    },
    appliedAt: '2025-01-25',
  },
  {
    _id: 'c2',
    vacancyId: '1',
    fullName: 'Ana García',
    email: 'ana.garcia@email.com',
    phone: '+52 33 2345 6789',
    cvPath: '/uploads/cvs/ana-garcia.pdf',
    status: 'screening',
    aiAnalysis: {
      score: 85,
      classification: 'ideal',
      summary: 'Desarrolladora con sólida experiencia en tecnologías requeridas.',
      strengths: ['React', 'Node.js', 'MongoDB', 'Buena comunicación'],
      concerns: ['Menos experiencia con Next.js'],
    },
    appliedAt: '2025-01-26',
  },
  {
    _id: 'c3',
    vacancyId: '2',
    fullName: 'Luis Hernández',
    email: 'luis.hernandez@email.com',
    phone: '+52 33 3456 7890',
    cvPath: '/uploads/cvs/luis-hernandez.pdf',
    status: 'interview',
    aiAnalysis: {
      score: 88,
      classification: 'ideal',
      summary: 'Diseñador con excelente portafolio y experiencia relevante.',
      strengths: ['Figma experto', 'UI Design', 'Prototyping', 'User Research'],
      concerns: ['Experiencia limitada en Adobe XD'],
    },
    appliedAt: '2025-01-27',
  },
  {
    _id: 'c4',
    vacancyId: '2',
    fullName: 'María López',
    email: 'maria.lopez@email.com',
    phone: '+52 81 4567 8901',
    cvPath: '/uploads/cvs/maria-lopez.pdf',
    status: 'applied',
    aiAnalysis: {
      score: 78,
      classification: 'potential',
      summary: 'Diseñadora con buen potencial, necesita más experiencia.',
      strengths: ['Figma', 'Creatividad', 'Pasión por el diseño'],
      concerns: ['Solo 2 años de experiencia', 'Portafolio limitado'],
    },
    appliedAt: '2025-01-28',
  },
  {
    _id: 'c5',
    vacancyId: '3',
    fullName: 'Roberto Sánchez',
    email: 'roberto.sanchez@email.com',
    phone: '+52 81 5678 9012',
    cvPath: '/uploads/cvs/roberto-sanchez.pdf',
    status: 'offer',
    aiAnalysis: {
      score: 90,
      classification: 'ideal',
      summary: 'Profesional de marketing con resultados comprobados.',
      strengths: ['SEO', 'SEM', 'Google Analytics', 'Liderazgo', 'ROI comprobado'],
      concerns: ['Ninguna'],
    },
    appliedAt: '2025-01-29',
  },
  {
    _id: 'c6',
    vacancyId: '4',
    fullName: 'Patricia Ramírez',
    email: 'patricia.ramirez@email.com',
    phone: '+52 55 6789 0123',
    cvPath: '/uploads/cvs/patricia-ramirez.pdf',
    status: 'screening',
    aiAnalysis: {
      score: 82,
      classification: 'ideal',
      summary: 'Analista con buen conocimiento de herramientas de datos.',
      strengths: ['SQL', 'Python', 'Tableau', 'Análisis estadístico'],
      concerns: ['Menos experiencia con Power BI'],
    },
    appliedAt: '2025-01-30',
  },
  {
    _id: 'c7',
    vacancyId: '5',
    fullName: 'Juan Torres',
    email: 'juan.torres@email.com',
    phone: '+52 477 7890 1234',
    cvPath: '/uploads/cvs/juan-torres.pdf',
    status: 'applied',
    aiAnalysis: {
      score: 75,
      classification: 'potential',
      summary: 'Estudiante con buena actitud y ganas de aprender.',
      strengths: ['Comunicación', 'Entusiasmo', 'Disponibilidad'],
      concerns: ['Sin experiencia laboral previa'],
    },
    appliedAt: '2025-01-31',
  },
  {
    _id: 'c8',
    vacancyId: '6',
    fullName: 'Fernando Díaz',
    email: 'fernando.diaz@email.com',
    phone: '+52 55 8901 2345',
    cvPath: '/uploads/cvs/fernando-diaz.pdf',
    status: 'interview',
    aiAnalysis: {
      score: 87,
      classification: 'ideal',
      summary: 'DevOps con experiencia sólida en AWS y containerización.',
      strengths: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
      concerns: ['Ninguna significativa'],
    },
    appliedAt: '2025-02-01',
  },
  {
    _id: 'c9',
    vacancyId: '7',
    fullName: 'Laura Morales',
    email: 'laura.morales@email.com',
    phone: '+52 55 9012 3456',
    cvPath: '/uploads/cvs/laura-morales.pdf',
    status: 'applied',
    aiAnalysis: {
      score: 84,
      classification: 'ideal',
      summary: 'Product Manager con experiencia en metodologías ágiles.',
      strengths: ['Product Strategy', 'Agile', 'Scrum', 'User Research'],
      concerns: ['Experiencia en industria diferente'],
    },
    appliedAt: '2025-02-02',
  },
  {
    _id: 'c10',
    vacancyId: '8',
    fullName: 'Miguel Flores',
    email: 'miguel.flores@email.com',
    phone: '+52 442 0123 4567',
    cvPath: '/uploads/cvs/miguel-flores.pdf',
    status: 'rejected',
    aiAnalysis: {
      score: 65,
      classification: 'no-fit',
      summary: 'Experiencia limitada para el nivel senior requerido.',
      strengths: ['Contabilidad básica', 'Excel'],
      concerns: ['Solo 3 años de experiencia', 'Sin experiencia en auditoría'],
    },
    appliedAt: '2025-02-03',
  },
  {
    _id: 'c11',
    vacancyId: '10',
    fullName: 'Sandra Vargas',
    email: 'sandra.vargas@email.com',
    phone: '+52 664 1234 5678',
    cvPath: '/uploads/cvs/sandra-vargas.pdf',
    status: 'screening',
    aiAnalysis: {
      score: 81,
      classification: 'potential',
      summary: 'Ingeniera QA con buenas bases en automatización.',
      strengths: ['Selenium', 'Jest', 'API Testing', 'Metodología'],
      concerns: ['Menos experiencia con Cypress'],
    },
    appliedAt: '2025-02-04',
  },
];

// Mock AI Agents (plantillas del sistema)
export const mockAIAgents = [
  {
    _id: 'agent-1',
    name: "Desarrollador Full Stack Senior",
    category: "desarrollo",
    isTemplate: true,
    description: "Agente especializado en evaluar perfiles de desarrolladores full stack senior, con énfasis en experiencia práctica y habilidades técnicas avanzadas.",
    criteria: {
      experience: { weight: 30, minYears: 5, importance: "high" },
      technicalSkills: { weight: 35, required: ["React", "Node.js", "TypeScript", "MongoDB", "Git"], desired: ["Next.js", "GraphQL", "AWS"] },
      education: { weight: 15, minLevel: "bachelor", required: false },
      softSkills: { weight: 10, keySkills: ["leadership", "teamwork", "communication"] },
      progression: { weight: 10 },
    },
    thresholds: { ideal: 80, potential: 65, review: 50 },
    systemPrompt: "Eres un Agente de Reclutamiento Técnico Especializado con 15 años de experiencia en desarrollo de software.",
    active: true,
    usageCount: 5,
    createdAt: '2025-01-10',
    updatedAt: '2025-01-10',
  },
  {
    _id: 'agent-2',
    name: "Desarrollador Full Stack Junior",
    category: "desarrollo",
    isTemplate: true,
    description: "Agente para evaluar perfiles junior, priorizando potencial, fundamentos técnicos y proyectos personales.",
    criteria: {
      experience: { weight: 15, minYears: 0, importance: "low" },
      technicalSkills: { weight: 40, required: ["JavaScript", "HTML", "CSS", "Git"], desired: ["React", "Node.js", "SQL"] },
      education: { weight: 25, minLevel: "associate", required: true },
      softSkills: { weight: 10, keySkills: ["learning-agility", "problem-solving", "teamwork"] },
      progression: { weight: 10 },
    },
    thresholds: { ideal: 75, potential: 60, review: 45 },
    systemPrompt: "Eres un Agente de Reclutamiento Técnico Especializado en perfiles junior.",
    active: true,
    usageCount: 3,
    createdAt: '2025-01-11',
    updatedAt: '2025-01-11',
  },
  {
    _id: 'agent-3',
    name: "Gerente de Proyecto Senior",
    category: "gerencia",
    isTemplate: true,
    description: "Agente para evaluar gerentes de proyecto con experiencia en metodologías ágiles.",
    criteria: {
      experience: { weight: 35, minYears: 7, importance: "high" },
      technicalSkills: { weight: 20, required: ["Scrum", "Kanban", "Jira"], desired: ["PMP", "SAFe"] },
      education: { weight: 15, minLevel: "bachelor", required: true },
      softSkills: { weight: 20, keySkills: ["leadership", "communication", "problem-solving"] },
      progression: { weight: 10 },
    },
    thresholds: { ideal: 85, potential: 70, review: 55 },
    systemPrompt: "Eres un Agente de Reclutamiento Especializado en Gerencia de Proyectos Senior.",
    active: true,
    usageCount: 2,
    createdAt: '2025-01-12',
    updatedAt: '2025-01-12',
  },
  {
    _id: 'agent-4',
    name: "Diseñador UX/UI",
    category: "diseño",
    isTemplate: true,
    description: "Agente para evaluar diseñadores UX/UI, enfocándose en portafolio y herramientas.",
    criteria: {
      experience: { weight: 25, minYears: 3, importance: "medium" },
      technicalSkills: { weight: 35, required: ["Figma", "Sketch", "User Research"], desired: ["HTML", "CSS"] },
      education: { weight: 15, minLevel: "bachelor", required: false },
      softSkills: { weight: 15, keySkills: ["empathy", "creativity", "communication"] },
      progression: { weight: 10 },
    },
    thresholds: { ideal: 80, potential: 65, review: 50 },
    systemPrompt: "Eres un Agente de Reclutamiento Especializado en Diseñadores UX/UI.",
    active: true,
    usageCount: 4,
    createdAt: '2025-01-13',
    updatedAt: '2025-01-13',
  },
];

// Flag para indicar si estamos usando mock data
let _usingMockData = false;

export function setMockDataMode(enabled: boolean) {
  _usingMockData = enabled;
}

export function usingMockData() {
  return _usingMockData;
}

